testDMS/Models/FUNDS.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNDS
    {
        public int FundID { get; set; }
        public string Fund { get; set; }
    }
}

testDMS/Controllers/FundController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using testDMS.DAL;
using testDMS.Models;
using Microsoft.AspNet.Identity;

namespace testDMS.Controllers
{


    public class FundController : Controller
    {
        private DonorManagementDatabaseEntities data = new DonorManagementDatabaseEntities();


        // GET: Fund
        public ActionResult Index()
        {
            return View(data.GLS);

        }


        // GET: Fund/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Fund/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "GLID,GL")] GLS gls)
        {
            try
            {
                data.GLS.Add(gls);
                data.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

               // GET: Fund/Delete/5
        public ActionResult Delete(int id)
        {

            GLS gl = data.GLS.Find(id);
            if (gl == null)
            {
                return HttpNotFound();
            }
            return View(gl);

        }

        // POST: Fund/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                GLS gl = data.GLS.Find(id);
                data.GLS.Remove(gl);
                data.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

testDMS/Views/Fund/Create.cshtml
@model testDMS.Models.GLS

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .panel > .panel-heading {
        background-image: none;
        background-color: #0096d7;
        color: white;
    }
</style>
<hr />
<div class="well well-lg">
    <div style="display: inline-block">
        <h4>Create New GL Code</h4>
    </div>
    <div style="display: inline-block;float:right">
        @Html.ActionLink("Back to GL Codes", "Index", "Fund", null, new { @class = "btn btn-default", @style = "background-color:#0096d7;color:white" })
    </div>
</div>

<br /><br />
<div class="panel panel-default">
    <div class="panel-heading">Enter a new GL code:</div>
    <div class="panel-body">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
<br /><br />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.GL, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.GL, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.GL, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" style="background-color:#0096d7;color:white"  />
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<div>
    @Html.ActionLink("Back to GL Codes", "Index", "Fund", null, new { @class = "btn btn-default", @style = "background-color:#0096d7;color:white" })
</div>

testDMS/Views/Fund/Delete.cshtml
@model testDMS.Models.GLS

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .panel > .panel-heading {
        background-image: none;
        background-color: #0096d7;
        color: white;
    }
</style>

<hr />
<div class="well well-lg">
    <div style="display: inline-block">
        <h4>Delete GL Code</h4>
    </div>
    <div style="display: inline-block;float:right">
        @Html.ActionLink("Back to GL Codes", "Index", "Fund", null, new { @class = "btn btn-default", @style = "background-color:#0096d7;color:white" })
    </div>
</div>

<br /><br />
<div class="panel panel-default">
    <div class="panel-heading">Delete GL Code:</div>
    <div class="panel-body">
        <h3 style="color:#E31B23">Are you sure you want to delete this?</h3>
        <div>
            <br /><br />
            <table class="table table-bordered" style="max-width:40%;font-size:large;" >
                <tr>
                    <td style="padding:6%">
                        GL Code:
                    </td>
                    <td style="padding:6%">
                        @Html.DisplayFor(model => model.GL)
                    </td>
                </tr>
            </table>
                   

            <br /><br />

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <div style="display: inline-block">
                        @Html.ActionLink("Back to GL Codes", "Index", "Fund", null, new { @class = "btn btn-default", @style = "background-color:#0096d7;color:white" })
                    </div>
                    <div style="display: inline-block;float:right">
                        <input type="submit" value="Delete" class="btn btn-default" style="background-color:#E31B23" />
                    </div>
                </div>
            }
        </div>
    </div>
</div>

testDMS/Views/Fund/Index.cshtml
@model IEnumerable<testDMS.Models.GLS>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .panel > .panel-heading {
    background-image: none;
    background-color: #0096d7;
    color: white;
}
</style>
<hr />
<div class="well well-lg">
    <div style="display: inline-block">
        <h4>GL Code Index</h4>
    </div>
    <div style="display: inline-block;float:right">
        @Html.ActionLink("Back to Donations", "Index", "Donations", null, new { @class = "btn btn-default", @style = "background-color:#0096d7;color:white" })
    </div>
</div>
<div style="display: inline-block">
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-default", @style = "background-color:#0096d7;color:white" })


</div>
<br /><br />
<div class="panel panel-default">
    <div class="panel-heading">GL Codes Index</div>
    <div class="panel-body">
        <table class="table table-striped" id="table" border="0" style="max-width:90%;margin:auto;">

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.GL)
                    </td>
                    <td>
                        @Html.ActionLink("Delete", "Delete", new { id = item.GLID })
                    </td>
                </tr>
            }

        </table>
    </div>
</div>