testDMS/Models/DONATION.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONATION()
        {
            this.FILES = new HashSet<FILES>();
        }
    
        public int DonationId { get; set; }
        public int DonorId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string TypeOf { get; set; }
        public Nullable<System.DateTime> DateRecieved { get; set; }
        public string GiftMethod { get; set; }
        public Nullable<System.DateTime> DateGiftMade { get; set; }
        public string GiftRestrictions { get; set; }
        public string Notes { get; set; }
        public string Fund { get; set; }
        public string GL { get; set; }
        public string Department { get; set; }
        public string Program { get; set; }
        public string GrantS { get; set; }
        public string Appeal { get; set; }
    
        public virtual DONOR DONOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILES> FILES { get; set; }
    }
}

testDMS/Models/DonationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace testDMS.Models
{
    public class DonationViewModel
    {
        public PagedList.IPagedList<DONATION> Donations { get; set; }
        public string searchString { get; set; }
        public int PageCount { get; set; }
        public int PageNumber { get; set; }
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
    }
}

testDMS/Controllers/DONATIONsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using testDMS.DAL;
using testDMS.Models;
using Microsoft.AspNet.Identity;

namespace testDMS.Controllers
{
    public class DONATIONsController : Controller
    {
        private DonorManagementDatabaseEntities ddlData = new DonorManagementDatabaseEntities();
        IDonorRepository drRepo;
        IDonationRepository dnRepo;
        private DonorManagementDatabaseEntities data = new DonorManagementDatabaseEntities();

        public DONATIONsController(IDonorRepository drRepo, IDonationRepository dnRepo)
        {
            this.drRepo = drRepo;
            this.dnRepo = dnRepo;
        }

        // GET: DONATIONs
        public ActionResult Index(string searchString, string sortOrder, string dateMade, string dateRecieved, int? page)
        {
            int count = 0;
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            ViewBag.CurrentSort = sortOrder;

            if (searchString == null)
            {

                ViewBag.DonationSortParam = String.IsNullOrEmpty(sortOrder) ? "donationID_desc" : "";
                ViewBag.DateSortParam = sortOrder == "DateGiftRecieved" ? "dateRecieved_desc" : "DateGiftRecieved";

                var donations = from DONATION d in dnRepo.GetDonations()
                                select d;

                count = donations.Count();
                //used to remove features for non-admin users.
                string userId = User.Identity.GetUserId();
                var user = data.AspNetUsers.FirstOrDefault(p => p.Id == userId);
                ViewBag.role = user.NewRole;

                DonationViewModel dvm = new DonationViewModel();
                //dvm.Donations = donations.Take(count).ToPagedList(pageNumber, pageSize);

                switch (sortOrder)
                {
                    case "donationID_desc":
                        donations = donations.OrderByDescending(d => d.DONOR.FName);
                        break;
                    case "DateGiftRecieved":
                        donations = donations.OrderBy(d => d.DateRecieved);
                        break;
                    case "dateRecieved_desc":
                        donations = donations.OrderByDescending(d => d.DateRecieved);
                        break;
                    default:
                        donations = donations.OrderBy(d => d.DONOR.FName);
                        break;

                }
                return View(donations.Take(count).ToPagedList(pageNumber, pageSize));
            }
            else
            {
                IEnumerable<DONATION> donation = (IEnumerable<DONATION>)dnRepo.FindBy(searchString);
                count = donation.Count();

                return View(donation.Take(count).ToPagedList(pageNumber, pageSize));
            }
        }

        // GET: DONATIONs/Details/5
        public ActionResult Details(int? ida, int? idb)
        {
            //if both the donor and donation id = 0 return a bad request message
            if (ida == null || idb == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            DONATION donation = dnRepo.FindById(ida, idb);

            if (donation == null)
            {
                return HttpNotFound();
            }

            return View(donation);
        }

        // GET: DONATIONs/Create
        public ActionResult Create()
        {
            ViewBag.DonorId = new SelectList(ddlData.DONOR, "DONORID", "FName");

            ViewBag.TypeOf = new SelectList(ddlData.TYPEOF, "TypeOf", "TypeOf");

            ViewBag.GiftMethod = new SelectList(ddlData.GIFTMETHOD, "GiftMethod", "GiftMethod");

            ViewBag.Fund = new SelectList(ddlData.FUNDS, "Fund", "Fund");

            ViewBag.GL = new SelectList(ddlData.GLS, "GL", "GL");

            ViewBag.Department = new SelectList(ddlData.DEPARTMENTS, "Department", "Department");

            ViewBag.Program = new SelectList(ddlData.PROGRAMS, "Program", "Program");

            ViewBag.Grant = new SelectList(ddlData.GRANTS, "GrantName", "GrantName");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DONATION myDonation, IEnumerable<HttpPostedFileBase> image)
        {
            DONATION donation = myDonation;
            List<FILES> myList = new List<FILES>();
            if (ModelState.IsValid)
            {
                foreach (var item in image)
                {
                    if (item != null && item.ContentLength > 0)
                    {
                        var myImage = new FILES
                        {
                            FileName = System.IO.Path.GetFileName(item.FileName),
                            ContentType = item.ContentType,
                            DonationId = donation.DonationId,
                            DonorId = donation.DonorId
                        };

                        using (var reader = new System.IO.BinaryReader(item.InputStream))
                        {
                            myImage.Content = reader.ReadBytes(item.ContentLength);
                        }

                        myList.Add(myImage);

                    }

                    donation.FILES = myList;
                }

                dnRepo.Add(donation);

                return RedirectToAction("Index");
            }

            ViewBag.DonorId = new SelectList(ddlData.DONOR, "DONORID", "FNAME", donation.DonorId);

            ViewBag.TypeOf = new SelectList(ddlData.DONATION, "TypeOf", "TypeOf");

            ViewBag.GiftMethod = new SelectList(ddlData.DONATION, "GiftMethod", "GiftMethod");

            ViewBag.Fund = new SelectList(ddlData.FUNDS, "Fund", "Fund");

            ViewBag.GL = new SelectList(ddlData.GLS, "GL", "GL");

            ViewBag.Department = new SelectList(ddlData.DEPARTMENTS, "Department", "Department");

            ViewBag.Program = new SelectList(ddlData.PROGRAMS, "Program", "Program");

            ViewBag.Grant = new SelectList(ddlData.GRANTS, "GrantName", "GrantName");

            return View(donation);
        }

        public ActionResult AddDonation(int id)
        {
            DONOR donor = drRepo.FindById(id);
            ViewBag.DonorId = id;
            ViewBag.DonorName = donor.FName;
            //CreateDonationViewModel cdvm = new CreateDonationViewModel();
            //cdvm.donor = donor;

            ViewBag.TypeOf = new SelectList(ddlData.TYPEOF, "TypeOf", "TypeOf");

            ViewBag.GiftMethod = new SelectList(ddlData.GIFTMETHOD, "GiftMethod", "GiftMethod");

            ViewBag.Fund = new SelectList(ddlData.FUNDS, "Fund", "Fund");

            ViewBag.GL = new SelectList(ddlData.GLS, "GL", "GL");

            ViewBag.Department = new SelectList(ddlData.DEPARTMENTS, "Department", "Department");

            ViewBag.Program = new SelectList(ddlData.PROGRAMS, "Program", "Program");

            ViewBag.Grant = new SelectList(ddlData.GRANTS, "GrantName", "GrantName");

            return View("~/Views/DONATIONs/DonorCreate.cshtml");//, cdvm
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddDonation(DONATION myDonation, IEnumerable<HttpPostedFileBase> image)
        {
            DONATION donation = myDonation;
            List<FILES> myList = new List<FILES>();
            if (ModelState.IsValid)
            {
                foreach (var item in image)
                {
                    if (item != null && item.ContentLength > 0)
                    {
                        var myImage = new FILES
                        {
                            FileName = System.IO.Path.GetFileName(item.FileName),
                            ContentType = item.ContentType,
                            DonationId = donation.DonationId,
                            DonorId = donation.DonorId
                        };

                        using (var reader = new System.IO.BinaryReader(item.InputStream))
                        {
                            myImage.Content = reader.ReadBytes(item.ContentLength);
                        }

                        myList.Add(myImage);

                    }

                    donation.FILES = myList;
                }

                dnRepo.Add(donation);
                return RedirectToAction("Details", "DONORs", new { id = donation.DonorId });
            }

            ViewBag.TypeOf = new SelectList(ddlData.TYPEOF, "TypeOf", "TypeOf");

            ViewBag.GiftMethod = new SelectList(ddlData.GIFTMETHOD, "GiftMethod", "GiftMethod");

            ViewBag.DonorId = new SelectList(ddlData.DONOR, "DONORID", "FNAME", donation.DonorId);

            ViewBag.Fund = new SelectList(ddlData.FUNDS, "Fund", "Fund");

            ViewBag.GL = new SelectList(ddlData.GLS, "GL", "GL");

            ViewBag.Department = new SelectList(ddlData.DEPARTMENTS, "Department", "Department");

            ViewBag.Program = new SelectList(ddlData.PROGRAMS, "Program", "Program");

            ViewBag.Grant = new SelectList(ddlData.GRANTS, "GrantName", "GrantName");


            return View("~/Views/DONATIONs/DonorCreate.cshtml", donation);
        }

        // GET: DONATIONs/Edit/5
        public ActionResult Edit(int? ida, int? idb)
        {
            if (ida == null || idb == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            DONATION donation = dnRepo.FindById(ida, idb);

            if (donation == null)
            {
                return HttpNotFound();
            }

testDMS/Views/Donations/Create.cshtml
@model testDMS.Models.DONATION

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<hr />
<div class="well well-lg">
    <div style="display: inline-block">
        <h4>Create Donation</h4>
</div>
        <div style="display: inline-block;float:right">
            @Html.ActionLink("Back to Home", "Index", "DONATIONs", null, new { @class = "btn btn-default", @style = "background-color:#0096d7;color:white" })
        </div>
    </div>

@using (Html.BeginForm("Create", "DONATIONs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>DONATION</h4>
        <hr />
        <table>
            <tr>
                <td>
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.DonorId, "DonorId", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.DonorId, ViewBag.DonorId as SelectList, htmlAttributes: new { @class = "form-control" } )
                            @Html.ValidationMessageFor(model => model.DonorId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Type", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("TypeOf", null, htmlAttributes: new { @class = "form-control" } )
                            @Html.ValidationMessageFor(model => model.TypeOf, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Gift Method", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("GiftMethod", null,  htmlAttributes: new { @class = "form-control" } )
                            @Html.ValidationMessageFor(model => model.GiftMethod, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    @*Add date box*@
                    <div class="form-group">
                        @Html.Label("Date Made", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DateGiftMade, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                            @Html.ValidationMessageFor(model => model.DateGiftMade, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    @*Add date box*@
                    <div class="form-group">
                        @Html.Label("Date Received", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DateRecieved, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                            @Html.ValidationMessageFor(model => model.DateRecieved, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Restrictions", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.GiftRestrictions, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.GiftRestrictions, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Fund, "Fund", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("Fund", null, htmlAttributes: new { @class = "form-control" } )
                            @Html.ValidationMessageFor(model => model.Fund, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.GL, "GL", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("GL", null, htmlAttributes: new { @class = "form-control" } )
                            @Html.ValidationMessageFor(model => model.GL, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Department, "Department", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("Department", null, htmlAttributes:  new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Program, "Program", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("Program", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Program, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.GrantS, "Grants", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("Grants", ViewBag.Grant as SelectList, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.GrantS, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Appeal, "Appeal", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Appeal, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Appeal, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Notes, "Notes", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextArea("Notes", null, new { @class = "form-control", @style = "max-width: 60%" })
                            @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
                        </div>
                    </div>

                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <div class="form-group">
                        <div>
                            @Html.TextBox("image", "", new { type = "file", name = "image[0]", multiple = "multiple" })
                            @Html.TextBox("image", "", new { type = "file", name = "image[1]", multiple = "multiple" })
                            </div>
                        </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="form-group">
                        <div class="col-md-offset-4 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </td>
            </tr>
        </table>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

testDMS/Views/Donations/Delete.cshtml
@model testDMS.Models.DONATION

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    td.lines {
        padding-bottom: 5px;
        padding-top: 5px;
        border-bottom: solid lightgray;
    }


    th {
        padding: 15px;
        text-align: center;
        width: 50%;
        background-color: #0096D7;
    }

    table {
        border-collapse: initial;
    }
</style>

<hr />
<div class="well well-lg">

    <div style="display: inline-block">
        <h4>Delete Donation Record: @Html.DisplayFor(model => model.DONOR.FName) @Html.DisplayFor(model => model.DONOR.LName)</h4>
    </div>

    <div style="display: inline-block;float:right">
        <input type="button" style="background-color:#0096D7;" class="btn btn-info" value="Back" onclick="location.href='@Url.Action("Index", "DONATIONs")'" />
    </div>
</div>

<div class="panel panel-default col-md-12">

    <div class="panel panel-heading"><h3 style="color:#e31b23">Are you sure you want to delete this donation record?</h3></div>

    <div class="panel panel-body">
        <table border="0">
            <tr><th class="lines" style="background-color:#0096D7" colspan="2">Donation Record</th><th>Check Image</th></tr>
            <tr>
                <td class="lines">Donor:  </td>
                <td class="lines">@Html.DisplayFor(model => model.DONOR.FName) @Html.DisplayFor(model => model.DONOR.LName)</td>
                <td rowspan="7" style="padding:3%">
                    <div class="form-group">
                        <br />
                    </div>
                </td>
            </tr>
            <tr>
                <td class="lines">Date Recieved: </td>
                <td class="lines"> @Html.DisplayFor(model => model.DateRecieved)</td>

            </tr>
            <tr><td class="lines">Amount:  </td><td class="lines">@Html.DisplayFor(model => model.Amount)</td></tr>
            <tr><td class="lines">Donation Type: </td><td class="lines"> @Html.DisplayFor(model => model.TypeOf)</td></tr>
            <tr><td class="lines">Method of Gift: </td><td class="lines"> @Html.DisplayFor(model => model.GiftMethod)</td></tr>
            <tr><td class="lines">Gift Date:  </td><td class="lines">@Html.DisplayFor(model => model.DateGiftMade)</td></tr>
            <tr><td class="lines">Restrictions: </td><td class="lines"> @Html.DisplayFor(model => model.GiftRestrictions)</td></tr>

            <tr><td colspan="3"><br />&nbsp;<input type="button" style="background-color:#0096D7;" class="btn btn-info" value="Back" onclick="location.href='@Url.Action("Index", "DONATIONs")'" /></td></tr>


        </table>
    </div>
</div>
<div>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color" style="text-align:right">
            <input type="submit" value="Delete" class="btn btn-default" style="background-color:#e31b23"/>

        </div>
    }
</div>

testDMS/Views/Donations/Details.cshtml
@model testDMS.Models.DONATION

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<style>
    td.lines {
                padding-bottom: 5px;
                padding-top: 5px;
                border-bottom: solid lightgray;
            }

            th {
                padding: 15px;
                text-align: center;
                width: 50%;
                background-color: #0096D7;
    }

            table {
                border-collapse: initial;
            }

            input[type=submit] {
                background: transparent url("../../Images/button_update-donation.png") 0 0 no-repeat;
                font-weight: bold;
                display: inline-block;
                text-align: center;
                cursor: pointer;
                height: 70px;
                width: 201px;
                border: 3px solid #fff;
        border-radius: 2em;
                color: transparent;
            }
</style>
<hr />
<div class="well well-lg">

    <div style="display: inline-block">
        <h4>Donation Record: @Html.DisplayFor(model => model.DONOR.FName) @Html.DisplayFor(model => model.DONOR.LName)</h4>
    </div>

    <div style="display: inline-block;float:right">
        <input type="button" style="background-color:#0096D7;" class="btn btn-info" value="Back" onclick="location.href='@Url.Action("Index", "DONATIONs")'" />
    </div>
</div>

<table border="0">
    <tr><th class="lines" style="background-color:#0096D7" colspan="2">Donation Record</th><th>Check Image</th></tr>
    <tr>
        <td class="lines">Donor:  </td>
        <td class="lines">@Html.DisplayFor(model => model.DONOR.FName) @Html.DisplayFor(model => model.DONOR.LName)</td>
        <td rowspan="8" style="padding:3%">
            <div class="form-group">
                <br />
                @if (Model.FILES.Count == 0)
        {
                    <div class="form-control-static">No Image Uploaded</div>
    }
                else
                { 
                    <img class="img-thumbnail"  src="@Url.Action("GetImageOne", "DONATIONs", new { Model.DonationId, Model.DonorId })" />
                    if (Model.FILES.Count > 1)
                    {
                        <img class="img-thumbnail"  src="@Url.Action("GetImageTwo", "DONATIONs", new { Model.DonationId, Model.DonorId })" />
                    }
                    else
                    {
                        <div class="form-control-static">Only One Image Uploaded</div>
                    }
                }
            </div>
        </td>
    </tr>
    <tr>
        <td class="lines">Date Recieved: </td>
        <td class="lines"> @Html.DisplayFor(model => model.DateRecieved)</td>
        
    </tr>
    <tr><td class="lines">Amount:  </td><td class="lines">@Html.DisplayFor(model => model.Amount)</td></tr>
    <tr><td class="lines">Donation Type: </td><td class="lines"> @Html.DisplayFor(model => model.TypeOf)</td></tr>
    <tr><td class="lines">Method of Gift: </td><td class="lines"> @Html.DisplayFor(model => model.GiftMethod)</td></tr>
    <tr><td class="lines">Gift Date:  </td><td class="lines">@Html.DisplayFor(model => model.DateGiftMade)</td></tr>
    <tr><td class="lines">Restrictions: </td><td class="lines"> @Html.DisplayFor(model => model.GiftRestrictions)</td></tr>
    <tr><td class="lines">Donation Notes: </td><td class="lines"> @Html.DisplayFor(model => model.Notes)</td></tr>
    <tr><td class="lines">Code:  </td><td class="lines">@Html.DisplayFor(model => model.Fund)-@Html.DisplayFor(model => model.GL)-@Html.DisplayFor(model => model.Department)@Html.Display(" ")@Html.DisplayFor(model => model.Program)-@Html.DisplayFor(model => model.GrantS)</td></tr>
    <tr><td colspan="3"><br />&nbsp;<input type="button" style="background-color:#0096D7;" class="btn btn-info" value="Back" onclick="location.href='@Url.Action("Index", "DONATIONs")'" /></td></tr>


</table>

<br />